name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    name: "Integration testing"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Set up the environment"
      run: docker-compose -f docker-compose.yml up -d 
    - name: "Show services"
      run: docker-compose ps --services
    - name: "Wait for Express server to be ready"
      run: |
        start_time=$(date +%s)
        timeout=0
        until docker-compose logs node-app 2>&1 | grep -q "Connected to MySQL database" || [ $timeout -eq 100 ]; do
            timeout=$((timeout+1))            
            sleep 1
        done
        if [ $timeout -eq 100 ]; then
            echo "Timeout reached waiting for Express server to be ready"
            exit 1
        fi
        end_time=$(date +%s)
        echo "Express server took $((end_time - start_time)) seconds to be ready"
    - name: "Test server"
      run: docker compose exec node-app npm run test 
      
  trivy_scan:
    name: "Trivy Scan"
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Install Trivy"
        run: |
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update && sudo apt-get install trivy
      - name: "Build Docker Image"
        run: docker build -t juanda99/node-app:latest ./app
        # This assumes your service using the built image is named 'your_service'
      - name: "Scan Docker Image"
        run: trivy  image --severity CRITICAL,HIGH --no-progress juanda99/node-app
