name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  tests:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Set up the environment"
      run: docker-compose -f docker-compose.yml up -d 
    - name: "Show services"
      run: docker-compose ps --services
    - name: "Wait for Express server to be ready"
      run: |
        start_time=$(date +%s)
        timeout=0
        until docker-compose logs node-app 2>&1 | grep -q "Connected to MySQL database" || [ $timeout -eq 100 ]; do
            timeout=$((timeout+1))            
            sleep 1
        done
        if [ $timeout -eq 100 ]; then
            echo "Timeout reached waiting for Express server to be ready"
            exit 1
        fi
        end_time=$(date +%s)
        echo "Express server took $((end_time - start_time)) seconds to be ready"
    - name: "Test server"
      run: docker compose exec node-app npm run test 
